X-lab2017/open-leaderboard

src/components/table.js
Signed-off-by: Yeming Gu <51205903090@stu.ecnu.edu.cn>
=> fix: update data name mapping

src/components/Dictionary.js, src/components/QA.js, src/components/header.css, src/components/header.js, src/index.js
=> feat: Responsive header

.gitignore, src/components/table.js
I have tested it manually. See the following screenshot:
=> Add a link to the personal GitHub account

src/components/table.js
=> feat: show March data

src/components/table.js
@LinuxSuRen did this work before, and I made some additions. Whether it's a project or developer, activity or influence, or whether to expand details, now there's a link to jump to GitHub.
Thanks again Rick!
=> feat: add url for actors and repos

src/Description.js, src/components/table.js, src/index.js
=> fix: Uniformly config year and month in index.js

.github/workflows/publish.yml
#16 
@frank-zsy can you help me review my code? This worked under my repo and I can get the correct change in OSS.
=> [feat] Add a github action for CI/CD

src/Description.js, src/components/datePicker.js, src/components/table.js, src/index.js
Get the newest updating timestamp automatically by fetching and parsing meta.json.
Initially, I set `year` and `month` to null, and use `useEffect` to fetch `meta.json`. After parsing the meta.json, use `setState` to update `year` and `month` and render whole page.
Signed-off-by: Yeming Gu <51205903090@stu.ecnu.edu.cn>
=> feat: Get the newest updating timestamp automatically

src/components/footer.js
fix: https://github.com/X-lab2017/open-leaderboard/issues/2
=> update GitHub links for OpenDigger and Leaderboard

src/components/Dictionary.js, src/util/i18n.js
=> fix: no blog url

src/Description.js, src/components/table.js, src/index.js, src/locales/en.json, src/locales/zh.json
fix: #26 
Signed-off-by: Yeming Gu <guyeming@bytedance.com>
=> fix: use correct month data

src/components/footer.js
=> fix: hide GitHub Logo before official confirmation

src/locales/zh.json
=> fix: locales

src/components/footer.js
=> feat: add GitHub official Icon!

src/components/table.js
Related issues:
- fix #59
- 将“全球”区域的大屏链接调整为可见
=> fix: Make the Insight link of 'global' visible.

src/components/header.js
Related issues:
- resolve #28 
- 进入页面后，点击切换语言按钮无法正确切换
=> fix: switching language problem

.github/workflows/publish.yml
Related: #65 
Hope this PR will be merged without bringing any fatal error to the deployment process!
=> ci: remove delete-oss from publish.yml

src/components/table.js, src/locales/en.json, src/locales/zh.json
Related issue：
- feature #70 
- 在洞察大屏图标列增加了中英文标题
- 修改了一部分的翻译问题
=> feat: add insight_board column title/modify translation mistakes

src/components/table.js
=> feature: update dashboard link

src/components/footer.js
related issue:
-  resolve #83 
调整了底部栏的布局，将原先的垂直设计调整为水平设计。
=> feat: adjust footer layout to horizontal

src/components/Dashboard.js, src/components/table.js
Related issues:
- resolve #88 
- replace all "https://dataease.nzcer.cn/" to "https://dataease.x-lab.info/"
=> refactor: replace dashboard link with new link

src/components/header.css, src/components/header.js
Added GitHub icon on the Header component to redirect to the GitHub repo, also added the change for mobile screen
=> feat: add GitHub icon on header

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other_issues.yml, .github/pull_request_template.md, README.md, src/Description.js, src/components/Dictionary.js, src/components/boardcard.js, src/components/footer.js, src/components/table.js, src/index.js
- resolve #92 
- 优化了部分代码的格式，主要是先前的几个PR改动，之前的改动未运行```npm run prettier```。
- 增加了issue和PR的模板，主要借鉴了hypercrx仓库的模板。
- 与之对应增加了README中的内容。
=> feat: add template for issue and PR

src/Description.js, src/components/table.js, src/constant.ts, src/index.js, src/locales/en.json, src/locales/zh.json
- resolve #95 
目前修改的情况为下图所示。在调试环境中，我设定在6号之前，数据还处于未更新状态，因此当我选择 `2023-06` 时，红圈位置会显示提示信息。在我提交 Commit 的内容里，我设定在4号之前。目前未更新状态时会显示上上个月的数据。
=> fix: change month judgment logic

.github/workflows/build.yml, src/index.js
- resolve #86 
add CI to trigger build on PR submission
=> ci: add CI to trigger build on PR submission

src/index.js
fix a minor bug introduced by #102
=> fix: displayed update time should be the same as updatedAt

src/components/QA2.js
- resolve #117 
I changed the position of close icon of modal to top. Also changed the anchor tag as it didn't had `href` to span tag maintaining the same design(CSS) for them.
[screen-capture.webm](https://github.com/X-lab2017/open-leaderboard/assets/84929607/599cabfd-52c3-49a9-aa5b-5fd87011b9c3)
=> [UI] Q&A section improved

src/components/table.js
=> feat:add user dashboard
